import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "./components/header/Header.jsx"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body>
        <div className="bg-main min-h-screen">
          {/* Пустой блок для отступа сверху с фоном */}
          <div className="h-[74px]"></div> 

          {/* Header без верхнего маргина */}
          <Header />

          {/* Остальной контент */}
          {children}
        </div>
      </body>
    </html>
  );
}
